### ISSUE TITLE
Metrics service port on Readme.md

### ISSUE THREAD

**Issue by chespinoza** [thingful/grow#41]
Seems that it's needed to update Readme file as it is pointing out 9001 as the port for prometheus and it seemed to be 3002 instead?

**Comment by Popcore** [comment]
@chespinoza port 3002 is used to expose metrics that can be collected in production by datadog. This is slightly different than port 9001 which is where the the Prometheus server will be available for inspection and graphing metics in a local environment only. Currently there is no plan to deploy this service in production.

**Comment by chespinoza** [comment]
Great, thanks for the explanation.
